### ISSUE TITLE
Implement Dataset class for PTB datasets

### ISSUE THREAD

**Issue by ishanfdo18098** [cepdnaclk/e18-4yp-GPU-Acceleration-for-Deep-Learning-based-Comprehensive-ECG-analysis#4]
- [ ] PTB-XL
- [ ] PTB-XL+

**Comment by ridmajayasundara** [comment]
I'll try this tomorrow

**Comment by ishanfdo18098** [comment]
> I'll do this tomorrow (assuming this is not urgent today)

Okay 🙂

**Comment by ishanfdo18098** [comment]
> I'll do this tomorrow (assuming this is not urgent today)

¯\\_(ツ)_/¯

**Comment by ridmajayasundara** [comment]
😅 working on it
